### ISSUE TITLE
"success-message" property should be optional

### ISSUE THREAD

**Issue by joseluisq** [huei90/angular-validation#190]
When I define `error-message` only It appears `success-message`: _"It's Required"_.

```html
<input type="text" 
  required-error-message="This filed is required">
  <!--  It's Required  -->
```

I think `success-message` message should be hidden by default.

_Note: Temporally this is soved via CSS:_

```css
.validation-valid {
  display: none;
}
```
